name: Make Release
on:
  push:
    tags:
    - '*'

env:
  REPOSITORY_NAME: Tile_S

  TIME_ZONE: Asia/Tokyo
  TIME_ZONE_PWSH: Tokyo Standard Time
  # Time zone for the timestamp when releasing.

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup aulua
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(gh api repos/karoterra/aviutl2-aulua/releases/latest --jq '.tag_name')
          archive="aulua-${tag}-windows-x64.zip"
          mkdir -p aulua
          gh release download -R karoterra/aviutl2-aulua $tag -p $archive -D aulua
          unzip aulua/$archive -d aulua
          echo `pwd`/aulua > $GITHUB_PATH

      - name: Create package
        run: |
          aulua pack
          cp build/package.au2pkg.zip "aviutl2_script_${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.au2pkg.zip"

      - name: Prepare release name
        id: release-name
        shell: pwsh
        run: |
          $name = "${{ github.ref_name }}"
          $date = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date).ToUniversalTime(), '${{ env.TIME_ZONE_PWSH }}')
          $formatted = $date.ToString('yyyy-MM-dd')
          echo "name=$name ($formatted)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

        # $phase = 0
        # Get-Content README.md | ForEach-Object {
        #   $line = $_
        #   if ($phase -eq 0) {
        #     if ($line -match '^(##*)\s*改版履歴\s*$') { $phase = 1 }
        #   }
        #   elseif ($phase -eq 1) {
        #     if ($line -match '^-\s') { $phase = 2 }
        #   }
        #   if ($phase -eq 1 -and $line -notmatch '^(-|##*)\s') {
        #     $line.Substring(2) | Add-Content ReleaseNotes.txt
        #   }
        # }

      - name: Prepare release notes
        id: release-notes
        run: |
          # windows runner does not correctly provide the time with this.
          # echo "name=${{ github.ref_name }} ($(TZ='${{ env.TIME_ZONE }}' date +'%Y-%m-%d'))" >> $GITHUB_OUTPUT
          echo "### 更新内容" >> ReleaseNotes.txt
          phase=0
          IFS=$'\n'
          cat README.md | while read line; do
            if [[ $phase == 0 ]]; then
              if [[ $line =~ ^##*[[:space:]]{1,}'改版履歴'[[:space:]]*$ ]]; then phase=1; fi
            elif [[ $phase == 1 ]]; then
              if [[ $line =~ ^-[[:space:]] ]]; then phase=2; fi
            elif [[ $line =~ ^(-|##*)[[:space:]] ]]; then break
            else
              echo ${line:2} >> ReleaseNotes.txt
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ steps.release-name.outputs.name }}
          files: '*.zip'
          body_path: ReleaseNotes.txt
